//ARTIFACT: Windows.Attack.Prefetch
.create table WindowsAttackPrefetch (
    Timestamp: datetime,
    Hostname: string,
    Name: string,
    ModTime: datetime,
    Modified: datetime,
    Artifact: string,
    Organization: string,
    ClientId: string,
    FlowId: string,
    IngestionTime: datetime
)

.create-or-alter function RouteWindowsAttackPrefetch() {
    RawVelociraptorEvents
    | where Artifact == "Windows.Attack.Prefetch"
    | extend 
        Name = tostring(RawData.Name),
        ModTime = todatetime(RawData.ModTime),
        Modified = todatetime(RawData.modified)
    | extend Timestamp = ModTime
    | project 
        Timestamp, 
        Hostname, 
        Name,
        ModTime,
        Modified,
        Artifact,
        Organization,
        ClientId, 
        FlowId, 
        IngestionTime
}

.alter table WindowsAttackPrefetch policy update @'[{"IsEnabled":true,"Source":"RawVelociraptorEvents","Query":"RouteWindowsAttackPrefetch()","IsTransactional":false}]'
